# 
# Prometheus Configuration
# 

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'soc-emulator'
    static_configs:
      - targets: ['soc-emulator:9100']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
